version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: product_service
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
#      - ./data:/data/db
volumes:
  mongo-data: